version: "2"
linters:
  enable:
    - dupword
    - errorlint
    - mirror
    - misspell
    - nolintlint
    - revive
    - testifylint
    - thelper
  settings:
    dupword:
      ignore:
        - FAIL
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: true
    revive:
      rules:
        - name: bare-return
        - name: blank-imports
        - name: comment-spacings
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: context-keys-type
        - name: defer
          arguments:
            - - call-chain
              - loop
        - name: dot-imports
        - name: early-return
        - name: empty-block
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: errorf
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: if-return
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: exported
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: time-equal
        - name: unexported-return
        - name: use-any
        - name: unreachable-code
        - name: unhandled-error
          arguments:
            - fmt.Print.*
            - fmt.Fprint.*
            - bytes.Buffer.Write.*
            - strings.Builder.Write.*
        - name: unused-parameter
        - name: unused-receiver
        - name: useless-break
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mfridman)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
