name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16", "1.17", "1.18"]
    env:
      VERBOSE: 1

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .

      - name: Run tests
        run: go test -count=1 -race ./parse -json -cover | ./tparse -notests -follow -all

      - name: Run tparse w/ std lib
        run: go test -count=1 fmt strings bytes bufio crypto log mime sort time -json -cover | ./tparse -follow -all

      - name: Run tparse w/ std lib
        run: |
          go test -count=1 fmt strings bytes bufio crypto log mime sort time -json -cover |\
            ./tparse -format=markdown >> $GITHUB_STEP_SUMMARY
