name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16", "1.17", "1.18"]
    env:
      VERBOSE: 1

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .

      - name: Run tests
        run: go test -count=1 -race ./parse -json -cover | ./tparse -all -top

      - name: Run tparse w/ std lib
        run: go test -count=1 fmt strings bytes bufio crypto log mime sort time -json -cover | ./tparse -pass

      - name: Run tparse w/ std lib into markdown file
        run: go test -count=1 fmt strings bytes bufio crypto log mime sort time -json -cover | ./tparse >> $GITHUB_STEP_SUMMARY
