name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17","1.18"]
    env:
      VERBOSE: 1

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .

      - name: Run tests with GITHUB_STEP_SUMMARY
        run: |
          go test -count=1 -race ./... -json -coverpkg github.com/mfridman/tparse/parse  | tee output.json | ./tparse -notests -follow -all
          NO_COLOR=1 ./tparse -format markdown -file output.json -all -slow 5 > $GITHUB_STEP_SUMMARY

      - name: Run tparse w/ std lib
        run: go test -count=1 fmt strings bytes bufio crypto log mime sort time -json -cover | ./tparse -follow -all

      # - name: Run tparse w/ std lib (GITHUB_STEP_SUMMARY)
      #   env:
      #     NO_COLOR: 1
      #   run: |
      #     go test -count=1 fmt strings bytes bufio crypto log mime sort time -json -cover |\
      #       ./tparse -format=markdown >> $GITHUB_STEP_SUMMARY
